/*
 * This file is generated by jOOQ.
 */
package domain.db;


import domain.db.tables.FlywaySchemaHistory;
import domain.db.tables.InvertedIndex;
import domain.db.tables.Message;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.inverted_index</code>.
     */
    public static final InvertedIndex INVERTED_INDEX = InvertedIndex.INVERTED_INDEX;

    /**
     * The table <code>public.message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;
}
