/*
 * This file is generated by jOOQ.
 */
package domain.db.tables.records;


import domain.db.tables.Message;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record5<Long, String, String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.message.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.message.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.message.sender</code>.
     */
    public void setSender(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.message.sender</code>.
     */
    public String getSender() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.message.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.message.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.message.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.message.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.message.created_ts</code>.
     */
    public void setCreatedTs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.message.created_ts</code>.
     */
    public Long getCreatedTs() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Message.MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Message.MESSAGE.SENDER;
    }

    @Override
    public Field<String> field3() {
        return Message.MESSAGE.CONTENT;
    }

    @Override
    public Field<Long> field4() {
        return Message.MESSAGE.CHAT_ID;
    }

    @Override
    public Field<Long> field5() {
        return Message.MESSAGE.CREATED_TS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSender();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public Long component4() {
        return getChatId();
    }

    @Override
    public Long component5() {
        return getCreatedTs();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSender();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public Long value4() {
        return getChatId();
    }

    @Override
    public Long value5() {
        return getCreatedTs();
    }

    @Override
    public MessageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecord value2(String value) {
        setSender(value);
        return this;
    }

    @Override
    public MessageRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public MessageRecord value4(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public MessageRecord value5(Long value) {
        setCreatedTs(value);
        return this;
    }

    @Override
    public MessageRecord values(Long value1, String value2, String value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Long id, String sender, String content, Long chatId, Long createdTs) {
        super(Message.MESSAGE);

        setId(id);
        setSender(sender);
        setContent(content);
        setChatId(chatId);
        setCreatedTs(createdTs);
    }
}
